
name : forward_to_beta

on :
  push :
    branches : [ alpha ]

jobs :

  forward :
    uses : Wandalen/RustModuleCd/.github/workflows/Forward.yml@master
    with :
      src_branch : 'alpha'
      dst_branch : 'beta'
    secrets :
      PRIVATE_GITHUB_BOT_TOKEN : '${{ secrets.PRIVATE_GITHUB_BOT_TOKEN }}'
