
name : forward_to_master

on :
  push :
    branches : [ beta ]

jobs :

  forward :
    uses : Wandalen/RustModuleCd/.github/workflows/Forward.yml@master
    with :
      src_branch : 'beta'
      dst_branch : 'master'
    secrets :
      PRIVATE_GITHUB_BOT_TOKEN : '${{ secrets.PRIVATE_GITHUB_BOT_TOKEN }}'
