name : wtools

on : push

env :
  CARGO_TERM_COLOR : always
  THE_MODULE : wtools

jobs :

  # wtools

  build :
    # if : "contains( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses : Wandalen/RustModuleArena/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/rust/wtools/Cargo.toml'

  build_fast :
    if : "!contains( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'wtools' )"
    uses : Wandalen/RustModuleArena/.github/workflows/RustFast.yml@master
    with :
      manifest_path : 'module/rust/wtools/Cargo.toml'
