name : module2

on : push

env :
  CARGO_TERM_COLOR : always
  THE_MODULE : module2

jobs :

  # module2

  build :
    # if : "contains( github.event.head_commit.message, '!build' ) || startsWith( github.event.head_commit.message, 'Merge' )"
    uses : Wandalen/RustModuleArena/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/module2/Cargo.toml'

  build_fast :
    if : "!contains( 'x', 'y' )"
    # if : "!contains( github.event.head_commit.message, '!build' ) && !startsWith( github.event.head_commit.message, 'Merge' ) && contains( github.event.head_commit.message, 'module2' )"
    uses : Wandalen/RustModuleArena/.github/workflows/RustFast.yml@master
    with :
      manifest_path : 'module/module2/Cargo.toml'
      module_name : 'module2'
