name : module2

on : push

env :
  CARGO_TERM_COLOR : always
  THE_MODULE : module2

jobs :

  # module2

  build :
    uses : Wandalen/RustModuleArena/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/module2/Cargo.toml'

  build_fast :
    uses : Wandalen/RustModuleArena/.github/workflows/RustFast2.yml@master
    with :
      manifest_path : 'module/module2/Cargo.toml'
      module_name : 'module2'
