name : module1

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # module1

  test :
    uses : Wandalen/RustModuleCdCi/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/module1/Cargo.toml'
      module_name : 'module1'
