name : module1

on : push

env :
  CARGO_TERM_COLOR : always
  THE_MODULE : module1

jobs :

  # module1

  build :
    uses : Wandalen/RustModuleArena/.github/workflows/RustFull.yml@master
    with :
      manifest_path : 'module/module1/Cargo.toml'

  build_fast :
    uses : Wandalen/RustModuleArena/.github/workflows/RustFast2.yml@master
    with :
      manifest_path : 'module/module1/Cargo.toml'
      module_name : 'module1'
