name : module2

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # module2

  test :
    uses : Wandalen/RustModuleCdCi/.github/workflows/StandardRustPush.yml@master
    with :
      manifest_path : 'module/module2/Cargo.toml'
      module_name : 'module2'
