
name : RustFast

on :
  workflow_call :
    inputs :
      manifest_path :
        required : true
        type : string
      module_name :
        required : true
        type : string

env :
  CARGO_TERM_COLOR : always
  WITH_SMOKE : false

jobs :

  fast :
    if : "!contains( github.event.head_commit.message, '!build' )
       && !startsWith( github.event.head_commit.message, 'Merge' )
       && contains( github.event.head_commit.message, inputs.module_name )"
    strategy :
      fail-fast : false
      matrix :
        os : [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on : ${{ matrix.os }}
    steps :
    - name : Install latest stable toolchain
      uses : actions-rs/toolchain@v1
      with :
        toolchain : stable
        override : true
    - uses : actions/checkout@v2
    # - name : Install cargo-hack
    #   run : cargo install cargo-hack
    - name : Run all tests
      run : cargo test --manifest-path ${{ inputs.manifest_path }}
    # - name : Run all tests with each feature
    #   run : cargo hack test --manifest-path ${{ inputs.manifest_path }} --each-feature
