
name : status_checks_rules_update

on :

  workflow_dispatch :
    inputs :
      pattern :
        description : 'A pattern to search workflows.'
        required : false
        type : string
        default : Module
      branch :
        description : 'A branch to setup status checks protection rules.'
        required : false
        type : string
        default : beta

concurrency :

  group : projected_rules_update
  cancel-in-progress : true

jobs :

  update :
    runs-on : ubuntu-latest
    steps :
      - uses: actions/checkout@v2
      - id: rules
        run: |
          WORKFLOWS=$(ls .github/workflows | grep ${{ inputs.pattern }})
          for WORKFLOW in $WORKFLOWS ; do
          CONTEXT=$(echo $WORKFLOW | sed 's/\(\S\+\).yml/{"context":"check (\1)","app_id":null}/')
            CONTEXTS="$CONTEXTS%0A$CONTEXT"
          done;
          CONTEXTS=$(sed 's/^%0A//g' <<< $CONTEXTS)
          CHECKS="[$(sed 's/%0A/,/g' <<< $CONTEXTS)]"
          echo "::set-output name=options::{\"required_status_checks\":{\"strict\":false,\"checks\":$CHECKS},\"enforce_admins\":false,\"required_pull_request_reviews\":null,\"restrictions\":null}"
      - run : |
          curl -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token \"${{ secrets.PRIVATE_GITHUB_BOT_TOKEN }}\"" \
          https://api.github.com/repos/${{ github.repository }}/branches/${{ inputs.branch }}/protection \
          -d ${{ steps.rules.outputs.options }}
