
name : wrong_branch_master

on :
  pull_request_target :
    branches :
      - main
      - master

jobs :

  # module2

  wrong_branch :
    uses : Wandalen/RustModuleCd/.github/workflows/WrongBranch.yml@master
    with :
      src_branch : 'beta'
      dst_branch : ${{github.base_ref}}
